name: Build Android APK and Release

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 29
          build-tools: 29.0.3

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Create config.properties file
        run: echo "${{ secrets.CONFIG_PROPERTIES }}" > app/config.properties

      - name: Decrypt keystore
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        run: |
          echo $ANDROID_KEYSTORE | base64 -d > app/keystore.jks
          mkdir -p /home/runner/.gradle
          mkdir -p /home/runner/.gradle/daemon
          mkdir -p /home/runner/.gradle/daemon/8.2
          echo $ANDROID_KEYSTORE | base64 -d > /home/runner/.gradle/daemon/8.2/keystore.jks

      - name: Build APK
        run: |
          ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=keystore.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
          --info
          
      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release.apk delfis.apk

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          release_name: "v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./delfis.apk
          asset_name: "delfis.apk"
          asset_content_type: application/vnd.android.package-archive
