name: Minimal Android CI Workflow

on:
  push:
    branches:
      - dev

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Create config.properties file
        run: echo "${{ secrets.CONFIG_PROPERTIES }}" > app/config.properties
          
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk 
          
  release:
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Download APK from build
        uses: actions/download-artifact@v4
        with:
          name: apk  
          
      - name: Rename APK
        run: mv app-debug.apk Delfis.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: Delfis.apk
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
